name: RiffleHouse
favicon: null
layout_spectrum: 0.9277591938152909
typography_spectrum: 0.8190978385973722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5230749619659036
  lightness: 0.3100576039869338
  saturation: 0.5677053441759199
  rhythmicContrast: 0.7278807950206101
purpose: []
